backend/timesheet/urls.py
from django.views.decorators.csrf import csrf_exempt

# from graphene_django.views import GraphQLView

from django.urls import path
from .views import calendar_app, approval_app, time_entries_view, time_entry_detail, form_entries, approve_user_entries
from .apis import get_all_users, get_user_time_entries, get_all_user_time_entries, get_user_time_entry_data
app_name = 'timesheet'

urlpatterns = [
    # views
    path('', calendar_app, name='calendar_app'),
    path('approval/', approval_app, name='approval_app'),
    path('approval/<int:pk>/', approve_user_entries, name=''),
    path('user_entries/', time_entries_view, name='time_entries_view'),
    path('user_entries/<int:pk>/', time_entry_detail, name='time_entry_detail'),
    path('user_entries/<int:year>/<int:month>/<int:day>/', time_entry_detail, name='time_entry_detail'),

    # api
    path('api/form_entries/', form_entries),
    path('api/get_users/', get_all_users, name='get_all_users'),
    path('api/get_all_user_time_entries/', get_all_user_time_entries, name='get_all_user_time_entries'),
    path('api/get_user_time_entries/', get_user_time_entries, name='get_all_users'),
    path('api/get_user_time_entry_data/', get_user_time_entry_data, name='get_user_time_entry_data')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

app_name = 'config'

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    # path('inventory/', include('backend.inventory.urls')),
    path('timesheet/', include('backend.timesheet.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('backend.accounts.urls')),
]

backend/timesheet/models.py
from django.db import models
from django.conf import settings

from django.core.validators import MinValueValidator, MaxValueValidator

from .timesheet_config import PAY_CYCLE_END_DATE

# Create your models here.

PAYRATE_CHOICES = [
    ('base', 'Base'),
    ('overtime', 'Overtime')
]


class PayPeriodManager(models.Manager):
    """
    Custom Manager that returns a list of entries that fall inside
    of a pay period
    """
    def get_current_pay_period_entries(self, pay_period):
        if isinstance(pay_period, str):
            pay_period = (int(pay_period.split('-')[0]), int(pay_period.split('-')[1]))

        entries = TimeData.objects.all()
        entry_values = entries.values()
        entry_pay_periods = [entry.pay_period_status() for entry in entries]
        filtered_pay_period_entries = []
        for values, entry_pay_period in zip(entry_values, entry_pay_periods):
            if pay_period == entry_pay_period:
                values['pay_period'] = entry_pay_period
                filtered_pay_period_entries.append(values)
        return filtered_pay_period_entries


class TimeData(models.Model):
    employee = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.RESTRICT
    )
    created = models.DateTimeField(auto_now_add=True)
    record_date = models.DateField()
    recorded_time = models.DecimalField(max_digits=6, decimal_places=2)
    comments = models.TextField()
    #overtime = models.BooleanField(default=False)
    overtime = models.CharField(max_length=8, choices=PAYRATE_CHOICES)
    entry_approved = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'Time Data'

    def pay_period_status(self):

        """
        Returns the pay period a time entry should be assigned to.
        For use in dashboard vue where approving time entries
        """

        from datetime import datetime
        from dateutil.relativedelta import relativedelta

        record_date_minus_month = self.record_date + relativedelta(months=-1)
        year = self.record_date.year
        month = self.record_date.month
        start_of_pay_cycle = datetime.strptime(f'{record_date_minus_month.year}-{record_date_minus_month.month}-{PAY_CYCLE_END_DATE + 1}', '%Y-%m-%d').date()
        end_of_pay_cycle = datetime.strptime(f'{year}-{month}-{PAY_CYCLE_END_DATE}', '%Y-%m-%d').date()

        if start_of_pay_cycle < self.record_date <= end_of_pay_cycle:
            return (year, month)
        elif self.record_date > end_of_pay_cycle:
            return (year, month + 1)
        elif self.record_date < start_of_pay_cycle:
            return (year, month - 1)

    objects = models.Manager()
    pay_period_entries = PayPeriodManager()


class PayPeriod(models.Model):
    set_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.RESTRICT)
    updated_on = models.DateField()
    pay_period_closure_date = models.IntegerField(
        validators=[
            MinValueValidator(1),
            MaxValueValidator(31)
        ]
    )

backend/timesheet/forms.py
from django import forms
from django.forms import ModelForm
from string import Template
from .models import TimeData

class TimeEntryDetailForm(forms.Form):
    #created = forms.DateTimeField()
    recorded_date = forms.DateField()
    hours = forms.IntegerField()
    minutes = forms.IntegerField()
    comments = forms.CharField(widget=forms.Textarea)
    overtime = forms.ChoiceField(
        choices=[('base', 'base'), ('overtime', 'overtime')])

class TimeEntryDetailModelForm(ModelForm):
    class Meta:
        model = TimeData
        fields = ['record_date', 'recorded_time', 'comments', 'overtime']

backend/timesheet/views.py
from datetime import datetime
import json

from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.core.serializers.json import DjangoJSONEncoder
from django.contrib.auth.decorators import login_required

from .timesheet_forms import FormCleaner, FormValidator
from .forms import TimeEntryDetailModelForm
from .models import TimeData

from backend.accounts.models import CustomUser



@login_required
def calendar_app(request):
    """

    :param request:
    :return:
    """
    if request.method == 'GET':
        # serve html and vue app
        return render(request, 'timesheet/time_capture_month.html')

    if request.method == 'POST':
        form = FormCleaner(request)
        validated_form = FormValidator(form.get_cleaned_form())

        # test form data with errors beloe
        # validated_form = FormValidator(
        #     {'dateRangePickerActive': False,
        #      'date': datetime.date(2022, 2, 26),
        #      # 'endDate': datetime.date(2022, 2, 25),
        #      'hours': 0,
        #      'minutes': 0,
        #      'comments': 'multi day',
        #      'payRate': 'overtime',
        #      'user_id': 1}
        # )
        # print(validated_form.errors)


        #write single or multi day entry to db
        if validated_form.is_valid_form:
            for item in validated_form:
                TimeData.objects.create(
                    employee=CustomUser.objects.get(id=item['user_id']),
                    record_date=item['date'],
                    recorded_time=(item['hours'] * 60 + item['minutes']),
                    comments=item['comments'],
                    overtime=item['payRate']
                )
            #  I want to return something else here, not HTTPResponseRedirect
            return HttpResponseRedirect(reverse('admin:index'))

        #if errors found during backend validation
        if not validated_form.is_valid_form:

            payload = {
                'is_valid_form': validated_form.is_valid_form,
                'error_dict': validated_form.get_form_errors()
            }

            return JsonResponse(payload)

def approval_app(request):
    """
    Serves Vue Approval App and handles time entry approvals
    :param request:
    :return:
    """
    if request.method == 'GET':
        return render(request, 'timesheet/timesheet_approval_app.html')

def approve_user_entries(request):
    pass

def time_entries_view(request):
    if request.method == 'GET':
        # print(request.user.id)
        user_obj = request.user.id

        year = request.GET.get('year', None)
        quarter = request.GET.get('quarter', None)
        month = request.GET.get('month', None)

        current_year = datetime.now().year

        year_filter_options = [current_year - 1, current_year, current_year + 1]

        if not all([year, quarter, month]):
            user_entries = TimeData.objects \
                .filter(employee=request.user) \
                .order_by('-record_date')

        else:

            user_entries = TimeData.objects \
                .filter(employee=request.user) \
                .filter(record_date__year=year)\
                .filter(record_date__month=month)\
                .order_by('-record_date')

        context = {
            'year_filter_options': year_filter_options,
            'user_entries': user_entries,
            'user_obj': user_obj
        }


        return render(request, 'timesheet/time_entries_view.html', context)

def time_entry_detail(request, year=None, month=None, day=None, pk=None):

    if request.method == 'POST':

        return HttpResponseRedirect(reverse('timesheet:time_entries_view'))

    elif request.method == 'GET':
        if pk:
            count_of_entries = 1
            time_entry = TimeData.objects.get(pk=pk)
            form = TimeEntryDetailModelForm(instance=time_entry)
            #print(getattr(time_entry, 'record_date'))
            # to properly format date to set value in js form
            date_str = datetime.strftime(getattr(time_entry, 'record_date'), '%Y-%m-%d')

        # handle returning values based on date
        if pk is None:
            time_entry = TimeData.objects.filter(record_date=f'{year}-{month}-{day}')
            count_of_entries = len(time_entry)

            if count_of_entries == 1:
                form = TimeEntryDetailModelForm(instance=time_entry[0])
                # to properly format date to set value in js form
                date_str = datetime.strftime(time_entry.values()[0].get('record_date'), '%Y-%m-%d')
            elif count_of_entries > 1:
                print(time_entry.values()[0]['comments'])
                multiple_time_entries = time_entry.values()

        context = {
            'form': form if count_of_entries == 1 else None,
            'count_of_entries': count_of_entries,
            'date': date_str if count_of_entries == 1 else None,
            'multiple_time_entries': multiple_time_entries if count_of_entries > 1 else None,
        }
    return render(request, 'timesheet/time_entry_detail.html', context)




#apis

def form_entries(request):
    if request.method == 'GET':
        user = request.user
        month = request.GET.get('month', '')
        year = request.GET.get('year', '')

        time_entries_json = None
        if month and year:
            month = int(month) + 1
            year = int(year)
            time_entries = TimeData.objects \
                .filter(employee=user.id) \
                .filter(
                    record_date__month=month,
                    record_date__year=year
                )

            time_entries_json = json.dumps(
                [entry for entry in time_entries.values()],
                default=str,
                cls=DjangoJSONEncoder
            )

    payload = {
        "time_entries_json": time_entries_json
    }

    return JsonResponse(payload)

templates/timesheet/time_capture_day.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/timesheet/time_entries_view.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
    <script defer src="{% static 'js/timesheet/time_entries_view.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/timesheet/time_entries_view.css' %}">
{% endblock styles%}

<h1>landing page</h1>



{% block content %}
<h1>User time entry view</h1>
<section>

</section>
<div class="container">
    <form method="GET" action="">
        {% csrf_token %}
        <div class="row">
            <div class="col-4">
                <select name="year" class="form-select form-select-sm" aria-label=".form-select-lg example">
                  <option selected>Year</option>
                    {% for item in year_filter_options %}
                        <option value="{{ item }}">{{ item }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-4">
                <select name="quarter" class="form-select form-select-sm" aria-label=".form-select-lg example">
                  <option selected>Quarter</option>
                  <option value="1">Q1</option>
                  <option value="2">Q2</option>
                  <option value="3">Q3</option>
                  <option value="3">Q4</option>
                </select>
            </div>
            <div class="col-4">
                <select name="month" class="form-select form-select-sm" aria-label=".form-select-lg example">
                  <option selected>Month</option>
                  <option value="1">January</option>
                  <option value="2">February</option>
                  <option value="3">March</option>
                  <option value="4">April</option>
                  <option value="5">May</option>
                  <option value="6">June</option>
                  <option value="7">July</option>
                  <option value="8">August</option>
                  <option value="9">September</option>
                  <option value="10">October</option>
                  <option value="11">November</option>
                  <option value="12">December</option>
                </select>
            </div>
        </div>
        <div class="row">
            <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary mt-3">Submit</button>
            </div>
        </div>
    </form>
</div>
<hr>
{##}
{#    <ul class="nav nav-tabs justify-content-center" id="myTab" role="tablist">#}
{#      <li class="nav-item" role="presentation">#}
{#        <button class="nav-link" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">Jan</button>#}
{#      </li>#}
{#        add "active class to show a month as selected#}
{#      <li class="nav-item" role="presentation">#}
{#        <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="false">Feb</button>#}
{#      </li>#}
{#      <li class="nav-item" role="presentation">#}
{#        <button class="nav-link" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact" type="button" role="tab" aria-controls="contact" aria-selected="false">Mar</button>#}
{#      </li>#}
{#      <li class="nav-item" role="presentation">#}
{#        <button class="nav-link" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="profile" aria-selected="true">Apr</button>#}
{#      </li>#}
{#      <li class="nav-item" role="presentation">#}
{#        <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="false">May</button>#}
{#      </li>#}
{#      <li class="nav-item" role="presentation">#}
{#        <button class="nav-link" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact" type="button" role="tab" aria-controls="contact" aria-selected="false">June</button>#}
{#      </li>#}
{#      <li class="nav-item" role="presentation">#}
{#        <button class="nav-link" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">July</button>#}
{#      </li>#}
{#      <li class="nav-item" role="presentation">#}
{#        <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="false">Aug</button>#}
{#      </li>#}
{#      <li class="nav-item" role="presentation">#}
{#        <button href="{% url 'timesheet:time_entries_view' 2021 9 %}" class="nav-link" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact" type="button" role="tab" aria-controls="contact" aria-selected="false">Sept</button>#}
{#      </li>#}
{#      <li class="nav-item" role="presentation">#}
{#          <a href="{% url 'timesheet:time_entries_view' 2021 9 %}">#}
{#              <button class="nav-link" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact" type="button" role="tab" aria-controls="contact" aria-selected="false">Sept</button>#}
{#          </a>#}
{#      </li>#}
{#      <li class="nav-item" role="presentation">#}
{#        <button class="nav-link" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">Oct</button>#}
{#      </li>#}
{#      <li class="nav-item" role="presentation">#}
{#        <button class="nav-link" id="contact-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="false">Nov</button>#}
{#      </li>#}
{#      <li class="nav-item" role="presentation">#}
{#        <button class="nav-link" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact" type="button" role="tab" aria-controls="contact" aria-selected="false">Dec</button>#}
{#      </li>#}
{#    </ul>#}
{#<div class="tab-content" id="myTabContent">#}
{#  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">...</div>#}
{#  <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">...</div>#}
{#  <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">...</div>#}
{#</div>#}

{#    </ul>#}

    User ID: {{ user_obj }}

<h3>User Entries</h3>
    {% for entry in user_entries %}
        <li>
        <a href="{% url 'timesheet:time_entry_detail' entry.pk %}">{{ entry.record_date }}</a>
        </li>
    {% endfor %}


{% endblock content %}

templates/timesheet/time_entry_detail.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
<h1>detail entry page</h1>
    <br>
    <h1>Form</h1>
    {% if count_of_entries == 1 %}
    <div id="single_form" class="container">
        <form action="" method="POST">
        {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="fieldWrapper">
                {{ form.record_date.errors }}
                <label for="{{ form.record_date.id_for_label }}"> Recorded Date: </label>
                <input value="{{ date }}" name="date" id="{{ form.recorded_date.id_for_label }}" type="date" class="form-control" placeholder="Date" required>
                {{ date }}
            </div>
            <div class="fieldWrapper">
                {{ form.recorded_time.errors }}
                <label for="{{ form.recorded_time.id_for_label }}">Time Worked: </label>
                <input value="{{ form.recorded_time.value }}" name="recorded_time" id="{{ form.recorded_time.id_for_label }}" type="number" class="form-control" min="0">
            </div>
            <div class="fieldWrapper">
                {{ form.comments.errors }}
                <label for="{{ form.comments.id_for_label }}">Comments: </label>
                <textarea name="comments" id="{{ form.comments.id_for_label }}" rows="1" class="form-control">{{ form.comments.value }}</textarea>
            </div>
            <div class="fieldWrapper">
                {{ form.overtime.errors }}
                <label for="{{ form.overtime.id_for_label }}">Pay Rate: </label>
{#                <input name="overtime" id="overtime" type="number" class="form-control" min="0">#}
                {{ form.overtime }}
            </div>
        <button class="btn btn-info mt-3">Submit</button>
        </form>
    </div>

    {% elif count_of_entries > 1%}
    <div id="multi_entry_table_display" class="container">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Date</th>
                    <th scope="col">Time Entry (minutes)</th>
                    <th scope="col">Comments</th>
                    <th scope="col">Pay Rate</th>
                </tr>
            </thead>
            <tbody>
            {% for entry in multiple_time_entries %}
            <tr>
                <td>{{ entry.record_date }}</td>
                <td>{{ entry.recorded_time }}</td>
                <td>{{ entry.comments }}</td>
                <td>{{ entry.overtime }}</td>
                <td><a href="{% url 'timesheet:time_entry_detail' entry.id %}">Modify?</a></td>

            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% endif %}

{% endblock content %}

templates/timesheet/timesheet_approval_app.html
{% extends 'base.html' %}
{% load render_bundle from webpack_loader %}
{% load static %}

{% block content %}
    <div id="app">
        {% render_bundle 'chunk-vendors' %}
        {% render_bundle 'timesheetTimeEntryApproval' %}
    </div>
{% endblock content %}