backend/timesheet/urls.py
from django.views.decorators.csrf import csrf_exempt

# from graphene_django.views import GraphQLView

from django.urls import path
from .views import calendar_app, approval_app, time_entries_view, time_entry_detail, form_entries, approve_user_entries
from .apis import get_all_users, get_user_time_entries, get_all_user_time_entries, get_user_time_entry_data
app_name = 'timesheet'

urlpatterns = [
    # views
    path('', calendar_app, name='calendar_app'),
    path('approval/', approval_app, name='approval_app'),
    path('approval/<int:pk>/', approve_user_entries, name=''),
    path('user_entries/', time_entries_view, name='time_entries_view'),
    path('user_entries/<int:pk>/', time_entry_detail, name='time_entry_detail'),
    path('user_entries/<int:year>/<int:month>/<int:day>/', time_entry_detail, name='time_entry_detail'),

    # api
    path('api/form_entries/', form_entries),
    path('api/get_users/', get_all_users, name='get_all_users'),
    path('api/get_all_user_time_entries/', get_all_user_time_entries, name='get_all_user_time_entries'),
    path('api/get_user_time_entries/', get_user_time_entries, name='get_all_users'),
    path('api/get_user_time_entry_data/', get_user_time_entry_data, name='get_user_time_entry_data')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

app_name = 'config'

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    # path('inventory/', include('backend.inventory.urls')),
    path('timesheet/', include('backend.timesheet.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('backend.accounts.urls')),
]

templates/base.html
<!DOCTYPE html>
{% load render_bundle from webpack_loader %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{% block title %}{% endblock title %}</title>
    {% block scripts %}{% endblock scripts %}
    {% block styles %}{% endblock styles%}

    <script type="text/javascript">
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            console.log(cookies)
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    const csrftoken = getCookie('csrftoken');

    </script>

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'timesheet:calendar_app' %}">Time Entry</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'timesheet:approval_app' %}">Time Approval</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'admin:index' %}" tabindex="-1">Admin</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

{% block content %}
{% endblock content %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

{% block javascript %}
{% endblock javascript %}

</body>
</html>